### PR TITLE
Set a sane umask to create a proper snap

### PR DESCRIPTION
**Pull request by sergiusens**
LP: #1515394

Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

### CODE REVIEW

**Comment by kyrofa** [comment]
Yeah I like it :+1:

**Comment by sergiusens** [comment]
This will be super naggy though

**Comment by kyrofa** [comment]
How so? Won't most people have 0022 or 0002

**Comment by sergiusens** [comment]
@kyrofa Naggy in the sense it will be spat out after every command that's run.

**Comment by kyrofa** [comment]
@sergiusens ah. I don't see a way around that, though, unless you touch, say, `parts/.umask_warned` or something. But honestly, enough is printed with every command I'm more worried this warning will be lost completely.

**Comment by jdstrand** [comment]
LGTM, thanks!

**Pull request closed without merging**
