### PR TITLE
Updating debian/changelog for the 0.5 release

### PR DESCRIPTION
**Pull request by sergiusens**
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

### CODE REVIEW

**Comment by elopio** [comment]
:100: nice progress on this release.

**Comment by kyrofa** [comment]
How did coverage decrease with a changelog entry? Looks good though.

**Comment by elopio** [comment]
@kyrofa the tests have not finished. As every suite reports it's coverage, the global number increases.

(wow github, I was just about to close this tab and magically the new comment appeared)

**Comment by kyrofa** [comment]
@elopio ah, good to know! And yeah, go ajax.

**Pull request merged**
