### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sergiusens**
Using the text from launchpad.

### CODE REVIEW

**Comment by ted-gould** [comment]
Can we make it link to the GitHub rendering of intro.md and tutorial.md?

https://github.com/ubuntu-core/snapcraft/blob/master/docs/intro.md

**Comment by sergiusens** [comment]
Done.

**Comment by ted-gould** [comment]
+1

**Comment by elopio** [comment]
Good, merge it.

**Comment by mvo5** [comment]
+1

**Pull request merged**
