### PR TITLE
Allow parts without a 'source' entry.

### PR DESCRIPTION
**Pull request by josepht**
LP:#1595666

Signed-off-by: Joe Talbott <joe.talbott@ubuntu.com>

### CODE REVIEW

**Comment by elopio** [comment]
lgtm. Maybe we can add a part without source to the wiki, so it will be parsed by the integration test.

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
El 24/06/16 a las 03:32, Leo Arias escribió:
> lgtm. Maybe we can add a part without source to the wiki, so it will be
> parsed by the integration test.

We have one, well I worked around it, but when this lands I can revert that.

**Comment by kyrofa** [comment]
ok to test

**Pull request merged**
