### PR TITLE
travis: remove the coveralls token

### PR DESCRIPTION
**Pull request by elopio**
LP: #1543675

### CODE REVIEW

**Comment by elopio** [comment]
Let's wait for the coveralls results to confirm that I am correct.

**Comment by kyrofa** [comment]
Why on earth isn't this required? Does it mean anyone can upload coverage for snapcraft?

**Comment by elopio** [comment]
Anyone can, but it will be reported to their branches. Coveralls separates the master coverage, and no PRs affect it.
I suppose that the trigger from travis hits an API that doesn't need a token, that's somehow not accessible to everybody. The details about this I don't understand.

**Comment by kyrofa** [comment]
Huh. Alright, I'm :+1: .

**Pull request merged**
