### PR TITLE
Support .git extension detection

### PR DESCRIPTION
**Pull request by didrocks**
On github for instance, the https URL for a repo ends with .git:
https://github.com/…/….git.
Detecting this pattern as source_type = 'git' enables us to support http{,s}
git repo distribution without having to mention it explicitely in
snapcraft.yaml.

### CODE REVIEW

**Comment by didrocks** [comment]
(Note that I added a trailing slash to the tests asset so that we don't have noisy diff if we add more pattern in the future :))

**Comment by kyrofa** [comment]
@didrocks that looks good, thank you! However, may I ask that you please create a bug for this and reference it in the commit with `LP: #<bugnumber>` on its own line? It helps us generate good changelogs.

**Comment by didrocks** [comment]
Sure! And this is now done! :)

**Comment by kyrofa** [comment]
@didrocks perfect thank you. Would you mind either rebasing or merging with master so we can make sure the tests run on the most recent version?

**Comment by didrocks** [comment]
just clicked on the github merge button to be on latest, let's have the tests rerunning then :)

**Comment by sergiusens** [comment]
El martes, 5 de abril de 2016 09h'33:45 ART, Didier Roche 
<notifications@github.com> escribió:
> just clicked on the github merge button to be on latest, let's 
> have the tests rerunning then :)

Thanks. This should be the first landing of 2.8.

For traceability we need to put the link of the PR into the bug report.


-- 
Enviado con Dekko desde mi dispositivo Ubuntu

**Comment by didrocks** [comment]
(done)

**Comment by sergiusens** [comment]
retest this please (and make sure the archive has no hash sum mismatches this time)

**Comment by sergiusens** [comment]
I' merging away, this is clearly an infra error.

**Pull request merged**
