### PR TITLE
gopase example: make it more usable

### PR DESCRIPTION
**Pull request by sergiusens**
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

### CODE REVIEW

**Comment by sergiusens** [comment]
This does not solve the fchown seccomp denial as I am hoping that gets fixed upstream

**Comment by elopio** [comment]
Now the service is running, which is progress. I still can't connect to 8080 from the host.
dmesg shows an apparmor DENIED for capname="net_admin". That's not the same as fchown.

**Comment by sergiusens** [comment]
Is the service really dying? I get a defunct service.

I'd merge this as is as it is much better than before; but the sqlite issue will bite; Is it maybe running under port 80 for you?

**Comment by elopio** [comment]
yes, I get the defunct gopasted process.
I agree that it's better than before, fwiw. :+1:

**Pull request merged**
