### PR TITLE
Fix typo in description: python2 -> python3

### PR DESCRIPTION
**Pull request by naufraghi**

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
Thanks @naufraghi!

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
ok to test

**Comment by kyrofa** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
Thanks @naufraghi, and welcome to the snapcraft project!

Could you please read and sign the contributors agreement?
http://www.ubuntu.com/legal/contributors

If you have any questions about it, please let us know.

About the change, +1.

**Comment by naufraghi** [comment]
ca signed, @elopio

**Comment by sergiusens** [comment]
Thanks for you contribution. I am glad you signed the CLA which would enable you to contribute in an easier fashion in the future. I must say though that for this specific change it wasn't really needed.

**Pull request merged**
