### PR TITLE
Fix list indentation in snapcraft-syntax.md. LP: #1531200

### PR DESCRIPTION
**Pull request by untriangle**
Align list syntax with Snappy documentation. Works both with github and the developer portal parser.
Fixes https://bugs.launchpad.net/developer-ubuntu-com/+bug/1531200

### CODE REVIEW

**Comment by dholbach** [comment]
:+1: Great work - this fixes: https://bugs.launchpad.net/developer-ubuntu-com/+bug/1531200 :-)

**Comment by kyrofa** [comment]
Thanks @untriangle! Can you please amend your commit to include the bug reference as described in the [contribution guide](https://github.com/ubuntu-core/snapcraft/blob/master/CONTRIBUTING.md)? Also, do you plan on making this change to 1.x as well?

**Comment by untriangle** [comment]
Having it on 1.x as well would be nice, indeed

**Comment by kyrofa** [comment]
@untriangle your commit message was what needed to be updated, not the PR title. Regarding the change to 1.x, it's not going to be a clean cherry-pick so if you guys want it there you'll have to make the change based on 1.x in a separate PR.

**Comment by kyrofa** [comment]
This has been fixed in #246, so I'll close this.

**Pull request closed without merging**
