### PR TITLE
Create the 'partial' directory for apt.

### PR DESCRIPTION
**Pull request by sergiusens**
LP: #1578007

Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

### CODE REVIEW

**Comment by sergiusens** [comment]
@mvo5 fwiw this is the solution I found to the problem, it seems 'partial' isn't created for us anymore.

**Comment by sergiusens** [comment]
Works on `yakkety` (tested in a container), also works on `xenial`

**Comment by kyrofa** [comment]
Blech. But :+1: .

**Comment by sergiusens** [comment]
Merging this for now even though it would be an `apt` bug to unblock us.

**Pull request merged**
