### PR TITLE
Improve error reporting

### PR DESCRIPTION
**Pull request by elopio**
This changes the way we exit on error to first log an error and then
exit with a status code of 1. The tests are updated for this new
behaviour.

A proper error when trying to upload an unexisting snap is also added.

LP: #1588023

### CODE REVIEW

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
Now I need to remember to update the squash and commit message :-)

**Comment by elopio** [comment]
This is good to go.  The only error is the ros problem, not caused by this branch.

**Pull request merged**
