### PR TITLE
autopkgtests: run the install examples tests in classic

### PR DESCRIPTION
**Pull request by elopio**
LP: #1572764

### CODE REVIEW

**Comment by elopio** [comment]
I'm internet handicapped, so I'm throwing this to CI. Plese wait for the tests to pass before doing a final review.

**Comment by kyrofa** [comment]
Looks good to me, though the autopkg tests are failing :+1:

**Comment by elopio** [comment]
Let's better wait for my other fixes on the examples suite. Thanks for the review kyle.

**Comment by sergiusens** [comment]
Eager to see you update the branch :smile:

**Comment by elopio** [comment]
almost forgot about this. Pushed and fingers crossed.

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
\o/

**Comment by kyrofa** [comment]
As I mentioned in standup I'm not a huge fan of focusing our examples on our test cases rather than as examples for developer usage, but I understand the difficulty here and I'm :+1: .

**Comment by elopio** [comment]
@kyrofa, well, we can have both. I can make it that it exits only if it receives a specific message. Care to report a bug about that?

**Comment by kyrofa** [comment]
> I can make it that it exits only if it receives a specific message. Care to report a bug about that?

Good idea-- [done](https://bugs.launchpad.net/snapcraft/+bug/1577867), with a low priority.

**Comment by elopio** [comment]
restest this please

**Comment by elopio** [comment]
\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/

**Pull request merged**
