### PR TITLE
examples_tests: added more tests after the snaps are installed

### PR DESCRIPTION
**Pull request by elopio**
Tests added for the examples gopaste, java-hello-world, opencv, shout,
tomcat-mave-webapp, webcam-webui and webchat.

LP: #1545071

### CODE REVIEW

**Comment by elopio** [comment]
retest this plea

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
retest this please

**Comment by sergiusens** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
@elopio what do you think about just adding a check if the service is running now and skip the http ones?

**Comment by elopio** [comment]
@sergiusens I followed your advice because IS said the connection is now open but we still can't access the ports. So this is ready to go, but now there are two new regressions in master that I need to debug.

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
This should be the first thing to get merged

**Comment by elopio** [comment]
@sergiusens it is ready. We got a green result in the last examples execution, but the autopkgtest one died of scalingstack complications.

**Comment by sergiusens** [comment]
:+1:

**Pull request merged**
