### PR TITLE
Shebang extraction

### PR DESCRIPTION
**Pull request by bjornt**
Extract the shebang of scripts that are used as binaries and have the wrapper script execute the shebang directly.

This way scripts can be used as a 'binary' in snapcraft.yaml, even if it uses an interpreter that is included in the snap itself. If the shebang points to the snap's 'install' directory when building the snap, the shebang will be extracted and the wrapper script will execute it directly using the $SNAP_APP_PATH environment variable.

This fixes these bugs:

    https://bugs.launchpad.net/snapcraft/+bug/1507357
    https://bugs.launchpad.net/snapcraft/+bug/1516404

The shebangs themselves aren't rewritten. In the future it would be nice to rewrite them to hide the local path of the one building the snap.

All unit tests pass.  I couldn't figure out how to run the plainbox tests, though.

### CODE REVIEW

**Comment by sergiusens** [comment]
This has conflicts, care to rebase or merge with master?

**Comment by sergiusens** [comment]
Aso, the `python2` plugin does something mostly similar, mind fixing that as well?

**Comment by sergiusens** [comment]
to run the `plainbox` tests just use the script to run unit and integration tests:

    ./runtests.sh

and to run the examples:

    ./runtest.sh plainbox examples

These tests lack on thing, and it is to check if the mentioned `binaries` have the right stuff in it.

**Comment by bjornt** [comment]
I've resolved the merge conflicts, did the same fix for the python2 plugin and added assertion of the contents of the binaries.

I still can't run the plainbox tests. I get this when trying to run them:

~/projects/snapcraft/integration-tests ~/projects/snapcraft
usage: manage.py [--help] [--version] [options]
manage.py: error: unrecognized arguments: -d /tmp/tmp.FfgGGZjPTd

**Comment by bjornt** [comment]
Ok, I've fixed the error in the traceback and the plainbox tests pass for me now.

**Comment by sergiusens** [comment]
Thanks for this :+1: 
I'll merge once I've done some testing (as our harness still doesn't run created snaps) unless @elopio wants to give his new one a shot :wink:

**Pull request merged**
