### PR TITLE
Update the assertion of the example install

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
Depends on #482

**Comment by elopio** [comment]
Moar progress, all of them install. Next, fix the bin path.

**Comment by kyrofa** [comment]
Awesome progress @elopio! :+1:

**Comment by elopio** [comment]
With Kyle's +1, I'm merging this. The next branch is running.

**Comment by sergiusens** [comment]
@elopio was my :+1: hidden?

**Comment by elopio** [comment]
@sergiusens it was too subtle. I was expending an standing ovation.

**Pull request merged**
