### PR TITLE
Replaced the double quotes by single quotes on strings.

### LINKED ISSUE #25: snapcraft is mixing the string literals, some with ' and some with "
Consistency is important, specially in the python world :)

So we should stick with only one form of string literals. Most of the canonical projects prefer single quotes.

So instead of "hello", use 'hello'

Launchpad Details: [#LP1476467](https://bugs.launchpad.net/bugs/1476467) Leo Arias - 2015-07-21 00:45:29 -0300

### PR DESCRIPTION
**Pull request by elopio**
Closes #25.
Consistency ftw!

### CODE REVIEW

**Comment by ted-gould** [comment]
Looks straight forward to me. Would love to know where that 0.2% coverage went :-)

**Comment by dholbach** [comment]
I'm not quite sure what happened, but https://coveralls.io/files/1403916637 is pointed out as having less coverage. The changes generally look good to me.

**Comment by sergiusens** [comment]
I think we need to stop running the plainbox tests in coverage mode.

**Comment by elopio** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 2015-11-02 04:56, sergiusens wrote:
> I think we need to stop running the plainbox tests in coverage
> mode.

I don't mind not reporting to coveralls the plainbox coverage.

But I think we need to add a test for autotools. That might solve two
problems, the weird coverage result and the uncovered module.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWOW/ZAAoJEIUvYw0No8DgwZsP/jtk5VKzZUWrE6UreaHTKjJl
Uf+8Z0R96CfQju11Yr/0jaOTiu4KqlhjopZXzvVMrpNO7ZCr8CaGuwHqerjm77zu
B9a1DHLjmLYDwFa1HQd72nwc4oPtralbXzOnw9lip5t6pQruAfEUKRZEltZrMdt1
2JhKBScGwEq5CdetiENfdu+qrPjQAdhbpXSgSWznXrx2Nj/Afcg7BQHx+v9jqgmw
xnKAePBxEx+TYWqxVpwWFYxFsdDlL6+wnXFNIk0h2UMqAIBj2EmbO69Gz/XN/RSX
Y6+DO0YXYb8mdJmMU+aReGA7ph83kvBa1HujHgmGU51fjnxdHl53iUn3IGx0xVJw
4V5sBojx351hVWHYoixI9mPryCls+tWMwBb9IWlShxAQWjvfl3HkmbGph3NWP5Nl
2AaY+xbOKlwor2oPXL9vR7sOcfikgPOSYifxODaLmT2g5bogffaB2Nd7+p15pH2J
30861rCA+fu7QdS6XXLXK1Ds/Um28HxcNHbEUxzZe4puFyvSJlA0/mrjt6YKzX+W
sWByDQvWIUOXnEKQrpkQVLnopsqj38wSoDhRLaASNpZCOJbTlp+xkxb10p9PgifY
/dN7xHOZvLJJM/WvhmPi8/844UDkyVWB31pL7pRROAnewiDCbvaJGYHZP2+a0BKm
a8XGVGqpclHVHfTGx426
=NHqz
-----END PGP SIGNATURE-----

**Pull request merged**
