### PR TITLE
Add environment variable to set Ubuntu release

### PR DESCRIPTION
**Pull request by jocave**
SNAPCRAFT_SOURCES_RELEASE used to set the Ubuntu release on non-local sources list.

### CODE REVIEW

**Comment by sergiusens** [comment]
A few questions arise:

- why an environment variable?
- why not in the part?
- is the use case plugins or parts?
- what is the use case?

And beating @elopio, maybe a test?

**Comment by sergiusens** [comment]
Can you get `master` rebased/merged to get the .travis.yml

**Comment by jocave** [comment]
* Why an environment variable?
This seemed like a complement to the SNAPCRAFT_LOCAL_SOURCES environment variable in that it was a customisation of the apt cache sources. Hence, chose to use the same mechanism to configure.

* Why not in the part?
Good question. Could be worth implementing in the part especially if there is a use case where you want to specify a different release for each part. Might be too much of corner case though.

Use case:
I wanted to force all packages declared in stage-packages to be from a particular Ubuntu release and specifically not the release that I was using on my development host. As it stood it was only possible for the apt cache generated for the parts to use the same Ubuntu release as the host given (in the non-local sources case) it was being pulled from platform.linux_distrubution()[2]

**Comment by sergiusens** [comment]
This is an alternate implementation https://github.com/ubuntu-core/snapcraft/pull/63

**Comment by sergiusens** [comment]
I'm going to close this one until we have further design guidance.

Thanks for bringing it up.

**Pull request closed without merging**
