### PR TITLE
Don't fail if there is no system library list

### PR DESCRIPTION
**Pull request by sergiusens**
LP: #1577750

Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

### CODE REVIEW

**Comment by kyrofa** [comment]
This looks good to me, though I'm trying to decide the use-case for this. Specifically, if someone is building a snap targeting a release that doesn't exist, it's not going to work, right? Why plow ahead and build that snap instead of erroring out? Maybe my complaint is more with the bug: it doesn't really describe why what's happening right now is a problem.

**Comment by kyrofa** [comment]
Oh, because it's coming from the running system, I see.

**Comment by sergiusens** [comment]
@kyrofa if it is of any use although you seem to have figured it out https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-yakkety/yakkety/amd64/s/snapcraft/20160503_064449@/log.gz :-)

**Comment by kyrofa** [comment]
Alright, combined with discussion on IRC, :+1: .

**Pull request merged**
