### PR TITLE
Remove information about PPA. snapcraft and tools will be kept up-to-date in xenial.

### PR DESCRIPTION
**Pull request by dholbach**
LP: #1554565

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by elopio** [comment]
:+1:

**Comment by elopio** [comment]
@dholbach even though this branch doesn't touch the tests, the new rules we set to the project require you to merge with master before we can land it.
can you please git rebase master ?

**Comment by dholbach** [comment]
I don't understand. This branch was up to date when I pushed it. :-(

**Comment by elopio** [comment]
@dholbach it's this new thing that we are trying called protected branches with required checks. When a branch lands, all the others need to be rebased because that's the only way to make sure that the tests will keep passing. And only the original author can do the rebase.
We are also trying other things, so feel free to hate it and yell.

**Comment by dholbach** [comment]
It's all right. It's just not a seamless experience for a contributor.

**Comment by sergiusens** [comment]
@dholbach sorry about the hassle but thanks as well!

**Pull request merged**
