### PR TITLE
Remove 'vendor' from snapcraft init template.

### PR DESCRIPTION
**Pull request by dholbach**
LP: #1536860

### CODE REVIEW

**Comment by kyrofa** [comment]
Oops, that's a little embarrassing, thanks for catching that! Perhaps we should remove `icon` as well and make this as bare-bones as possible. Thoughts?

**Comment by elopio** [comment]
:+1:
I'm not sure about removing the icon. Do we want to make it bare-bones, or to showcase all the features? Maybe we can put in a comment that it is optional and can be removed.

**Comment by kyrofa** [comment]
@elopio yeah I'm good with that. @dholbach can you just add a "This is optional." sentence to the end of the icon comment?

**Comment by kyrofa** [comment]
We should add a test to validate this yaml, but that's a different PR. Thanks @dholbach!

**Pull request merged**
