### PR TITLE
docs - Fix indentation of 'cam' example.

### PR DESCRIPTION
**Pull request by josepht**
Line up the filesets.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
@josepht thanks for fixing that! Please take a look at our [contribution guide](https://github.com/ubuntu-core/snapcraft/blob/master/CONTRIBUTING.md). Typically we require a bug per PR, but since this is a pretty small documentation fix we'll let that slide :smiley: . However, you do need to sign the CLA, please.

**Comment by kyrofa** [comment]
@josepht scratch that-- can you just amend your commit and change the email address to your canonical one?

**Comment by kyrofa** [comment]
Oh nevermind, I need to just fix the CLA checker script to also check for Canonical membership. This PR is fine.

**Comment by sergiusens** [comment]
Hi there, we don't do merges, we do rebases and require one commit per PR as described in `CONTRIBUTING.md`

**Comment by kyrofa** [comment]
Sorry @josepht would you mind rebasing once more? The tests never responded so we didn't get this in before other items.

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by josepht** [comment]
I'm not sure how this PR got closed.

**Comment by kyrofa** [comment]
Hmm... it says you did. And I can't reopen it :stuck_out_tongue: .

**Comment by josepht** [comment]
I pushed the original branch. :-)

**Comment by kyrofa** [comment]
retest this please.

**Pull request merged**
