### PR TITLE
Support updating cache without content-length

### PR DESCRIPTION
**Pull request by sergiusens**
LP: #1595610

Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

### CODE REVIEW

**Comment by sergiusens** [comment]
Still has 100% coverage

**Comment by elopio** [comment]
nice! I liked that test.

**Comment by sergiusens** [comment]
retest this please

why oh why

**Comment by sergiusens** [comment]
retest this please

**Comment by elopio** [comment]
good to land. #597 shows that the integration tests now pass.

**Pull request merged**
