### PR TITLE
Fix Snap icons for Demos

### PR DESCRIPTION
**Pull request by RobLoach**
The demos use `icons:` in the `snapcraft.yml` files. This PR [fixes the assets](https://github.com/ubuntu-core/snapcraft/blob/master/docs/metadata.md#fixed-assets) and moves the icons to `setup/gui/icon.png`.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Hi thanks for your contributions. I would like to see the icons removed complely from these as they aren't even relevant icons.

Do you mind doing that as well (instead of moving them).

**Comment by RobLoach** [comment]
@sergiusens Thanks! Deleted each one.

**Comment by sergiusens** [comment]
ok to test

**Comment by sergiusens** [comment]
retest this please

**Comment by RobLoach** [comment]
Thanks, sergiusens :+1:

**Pull request merged**
