### PR TITLE
Support the source-subdir keyword for parts

### PR DESCRIPTION
**Pull request by sergiusens**
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

### CODE REVIEW

**Comment by elopio** [comment]
What I see looks good, but this confuses me and requires the plugins to be extra careful.
Would it be possible for the pull step to leave only the right subdir in the build directory?

**Comment by sergiusens** [comment]
@elopio I could, but then all *vcs* managed sources lose their meaning a bit.

**Comment by ted-gould** [comment]
I can't find anything wrong, I really wanted to find a missing os.path.join() ;-) IMHO, plugins should do it right, we do control those and can test it.

**Comment by sergiusens** [comment]
So the pro for this path is that we keep the original source integrity. The con is, the complexity is moved over to the plugins.

Since we said the build step is in charge of looking after which sources to use for building, I think this is a good compromise. If this becomes a problem we can look into:

- untarring specific subdirs only
- `bzr export`
- `hg export`
- `git archive`
- and local source management (this would be the most trivial)

**Pull request merged**
