### PR TITLE
Release changelog for 2.3

### PR DESCRIPTION
**Pull request by sergiusens**
Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

### CODE REVIEW

**Comment by sergiusens** [comment]
I see this when running `gbp buildpackage` locally
```
======================================================================
ERROR: test_devel_version (snapcraft.tests.test_main.TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/sergiusens/source/github.com/ubuntu-core/snapcraft/snapcraft/tests/test_main.py", line 92, in test_devel_version
    snapcraft.main.main()
  File "/home/sergiusens/source/github.com/ubuntu-core/snapcraft/snapcraft/main.py", line 98, in main
    log.configure()
  File "/home/sergiusens/source/github.com/ubuntu-core/snapcraft/snapcraft/log.py", line 45, in configure
    sys.stdout.detach(), encoding='UTF-8', line_buffering=True)
io.UnsupportedOperation: detach

----------------------------------------------------------------------
```

**Comment by elopio** [comment]
:+1:

**Comment by sergiusens** [comment]
Builds fine here https://launchpad.net/~snappy-dev/+archive/ubuntu/snapcraft-daily/+packages?field.name_filter=snapcraft&field.status_filter=published&field.series_filter=xenial fwiw

**Comment by kyrofa** [comment]
Looks great!

**Pull request merged**
