### PR TITLE
Correct autotools documentation and tests to use configflags

### PR DESCRIPTION
**Pull request by flexiondotorg**
As discussed in #snappy IRC on Freenode with `sergiusens` at 13:41:02 on 26th May 2016, here is a pull request to correct the autotools plugin documentation and a couple of test cases.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
OK to test

**Comment by sergiusens** [comment]
While these tests run, let me say thank you for your contribution!

**Comment by kyrofa** [comment]
Wow, I never noticed this. :+1:

**Pull request merged**
