### PR TITLE
Add SNAP_LIBRARY_PATH to LD_LIBRARY_PATH.

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves LP: [#1570945](https://bugs.launchpad.net/snapcraft/+bug/1570945)

### CODE REVIEW

**Comment by mvo5** [comment]
\o/ Thank you!

**Comment by elopio** [comment]
:+1:

**Comment by sergiusens** [comment]
This looks familiar :wink: :+1:

**Comment by kyrofa** [comment]
retest this please

**Comment by mvo5** [comment]
@sergiusens It was "inspired" by a top notch developers pastebin :P and fortunately @kyrofa fixed all the tests. You guys rock!

**Comment by elopio** [comment]
restest this please

**Comment by elopio** [comment]
restest this please

**Comment by elopio** [comment]
restest this please

**Pull request merged**
