### PR TITLE
Make the series for the stage packages a value that can be set by the part or the plugin

### PR DESCRIPTION
**Pull request by ted-gould**

### CODE REVIEW

**Comment by sergiusens** [comment]
This is an alternate implementation https://github.com/ubuntu-core/snapcraft/pull/54

While I like this better, please talk to the launchpad folk as this breaks some assumptions.
This is also an inflexion point in direction; do we want to support this model or be more like `debuild`?

**Comment by sergiusens** [comment]
This should close issue #37

**Comment by ted-gould** [comment]
I'm not sure how this breaks LP, I think that they just want us to access the archive at a given time, I don't think they care what series we access when.

**Comment by sergiusens** [comment]
So I need @niemeyer's opinion as this is a spec change/addtition

**Comment by sergiusens** [comment]
Thanks for working on this but, I'm closing this until further notice as it currently does not fit the project goals.

**Pull request closed without merging**
