### PR TITLE
Remove the unittests from the autopkgtest execution

### PR DESCRIPTION
**Pull request by elopio**
The tests were being run twice, once when building the package and
then on the autopkg execution.

LP: #1596068

### CODE REVIEW

**Comment by sergiusens** [comment]
I will wait for autopackage to work again before taking this one in ;-)

**Comment by elopio** [comment]
what could possibly go wrong? ;)
it's almost ready.

**Comment by kyrofa** [comment]
I seem to remember someone saying "30 minutes" about 5 hours ago or so.

**Comment by elopio** [comment]
http://devopsreactions.tumblr.com/post/139593622302/so-all-your-estimates-were-random

**Comment by kyrofa** [comment]
:stuck_out_tongue:

**Comment by sergiusens** [comment]
@elopio how about an update branch here? :-)

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
All green. It took so long to execute because of https://bugs.launchpad.net/snappy/+bug/1596243

**Pull request merged**
