### PR TITLE
Close fd on invalid credentials for upload

### PR DESCRIPTION
**Pull request by sergiusens**

### CODE REVIEW

**Comment by sergiusens** [comment]
this depends on #284

**Comment by elopio** [comment]
ok to me.

**Comment by ricardokirkner** [comment]
LGTM. Would it no be possible to add a test to ensure file is closed after error from wrong credentials?

**Comment by kyrofa** [comment]
Looks fine, though check the title before merge.

**Comment by kyrofa** [comment]
Note that this bug is fixed in PR #283

**Pull request closed without merging**
