### PR TITLE
Added the travis configuration file.

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
Work in progress, checking the travis results. Do not merge yet.

**Comment by elopio** [comment]
This is failing because of mvo5/godd/pull/2
Good tests!

**Comment by mvo5** [comment]
The code looks good! +1
However travis is failing right now with:
"""
Failed doing pull for godd: Command '['/bin/sh', '/tmp/tmpom5ikm9f', 'env', 'GOPATH=/home/travis/.cache/plainbox/sessions/pbox-newm8u2w.session/CHECKBOX_DATA/parts/godd/build', 'go', 'get', '-t', '-d', 'github.com/mvo5/godd']' returned non-zero exit status 1
"""

**Comment by mvo5** [comment]
Uh, I am fixing the godd test now, sorry for the trouble, looks like a incorrect commit.

**Comment by mvo5** [comment]
Now it fails with:
""""
Failed doing pull for qml: qtdeclarative5-qtmir-plugin
...
Outcome: job failed
""""
which happens because qtdeclarative5-qtmir-plugin is only available on vivid and later and the build is run on a trusty host. Maybe its in the SDK ppa and we could add it from there?

**Comment by elopio** [comment]
I will move the plainbox examples suite to another branch so we can land this now.
And taking mvo's +1, I'll do it now.

**Comment by elopio** [comment]
ah, except that I can't merge anything. @sergiusens please, do the honors.

**Pull request merged**
