### PR TITLE
Fix missing python-magic dependency

### PR DESCRIPTION
**Pull request by fallen**
See https://bugs.launchpad.net/snapcraft/+bug/1568901

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Is it called python-magic on pypi?

**Comment by fallen** [comment]
Yes : https://pypi.python.org/pypi/python-magic

**Comment by fallen** [comment]
Maybe I should rewrite the commit and sort the dependencies by alphabetical order?

**Comment by fallen** [comment]
Ah, I just noticed there is also https://pypi.python.org/pypi/filemagic ... both seem to implement a magic package interfacing with libmagic ...

**Comment by sergiusens** [comment]
El 11/04/16 a las 12:21, Yann Sionneau escribió:
> Ah, I just noticed there is also https://pypi.python.org/pypi/filemagic
> ... both seem to implement a magic package interfacing with libmagic ...
Exactly, make sure you get the correct one ;-)

**Comment by kyrofa** [comment]
@fallen thanks for the contribution! Please also take a look at the [contribution guide](https://github.com/ubuntu-core/snapcraft/blob/master/CONTRIBUTING.md). Please make sure you've signed the CLA, and also make sure you reference the bug within the commit itself.

**Comment by fallen** [comment]
oh, and a 3rd one : https://pypi.python.org/pypi/file-magic

Anyway, in your commit ( 4a5de243ea8e39d32134b8d9cd20a8ff113258e3 ) you tell to install via pip "file-magic" but in the debian/control you add the python-magic dependency. So there is already a consistency issue.

Maybe we should switch everything to python-magic because it's the most recent one and the most downloaded one on pypi?
Any other idea?

**Comment by fallen** [comment]
@kyrofa Thanks for the reminder! When I'll rewrite the commit I'll add the missing LP line.
But yes, I've signed the CLA and I've been added to the corresponding launchpad group :)

**Comment by kyrofa** [comment]
@fallen please make sure you commit using an email address associated with your LP account then, so we can verify (your current one is not :smiley:).

**Comment by fallen** [comment]
@kyrofa Thanks, it should be OK now I've just added some missing email addresses on my launchpad account :)

**Comment by kyrofa** [comment]
@fallen perfect, thanks! CLA verified.

**Comment by sergiusens** [comment]
Sorry for taking so long, this got lost from my radar.

By looking at

```
$ apt show python3-magic 
Package: python3-magic
Version: 1:5.25-2ubuntu1
Priority: extra
Section: python
Source: file
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Christoph Biedl <debian.axhn@manchmal.in-ulm.de>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 54.3 kB
Depends: python3:any (>= 3.3.2-2~), libmagic1 (>= 1:5.25-2ubuntu1), libmagic1 (<< 1:5.25-2ubuntu1.1~)
Homepage: http://www.darwinsys.com/file/
Task: ubuntu-sdk
Supported: 5y
Download-Size: 5,438 B
APT-Manual-Installed: no
APT-Sources: http://ubuntu.unc.edu.ar/ubuntu xenial/main amd64 Packages
Description: File type determination library using "magic" numbers (Python 3 bindings)
 This library can be used to classify files according to magic
 number tests. It implements the core functionality of the file
 command.
 .
 This package contains the Python 3 bindings.
```

It seems that the correct dependency to use is https://pypi.python.org/pypi/file-magic

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
ok to test

**Comment by fallen** [comment]
Can someone merge this?
Or maybe merge this one instead https://github.com/ubuntu-core/snapcraft/pull/550 ?

**Pull request merged**
