### PR TITLE
Temporary skip the webcam example while we debug the pip issue.

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by kyrofa** [comment]
:+1: just waiting on the tests (should be the first one that passes!)

**Comment by kyrofa** [comment]
Or not.

**Comment by sergiusens** [comment]
I thought we were going to try and lock it down to a specific version (pyyaml)

**Comment by elopio** [comment]
@sergiusens the links you gave us point to an out of memory issue, but I'm not sure how you got to pyyaml. The last pyyaml update in pypi was two years ago.

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Pull request merged**
